### ISSUE TITLE
npm i doesnt work; NPm registry missin

### ISSUE THREAD

**Issue by ghost** [dogegarden/dogehouse-api#34]
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/dogehouse-js/-/dogehouse-js-0.1.0.tgz - Not found
npm ERR! 404 
npm ERR! 404  'dogehouse-js@http://registry.npmjs.org/dogehouse-js/-/dogehouse-js-0.1.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krishnaramasimha/.npm/_logs/2021-04-10T14_24_37_210Z-debug.log

**Comment by raikasdev** [comment]
It is dogehouse.js, not dogehouse-js

**Comment by ghost** [comment]
Try cloning the repo and running npm i

**Comment by ghost** [comment]
It won't work

**Comment by Mudrank** [comment]
don't clone the repo

**Comment by crispyaus** [comment]
Working on a new TS version.
