### ISSUE TITLE
User endpoint

### ISSUE THREAD

**Issue by IntegraterGithub** [dogegarden/dogehouse-api#50]
A user stats endpoint would be good.

**Comment by s3ansh33p** [comment]
There is an endpoint for users and rooms. 
User: https://api.dogegarden.net/v1/search/admin
Room: https://api.dogegarden.net/v1/search/lofi?type=room

This may change in the future to https://api.dogegarden.net/v1/user/ and https://api.dogegarden.net/v1/room/

**Comment by crispyaus** [comment]
added /v1/user/ID or Username 

you can now get a user directly instead of search. #52
